[rospy.client][INFO] 2024-07-18 15:09:09,449: init_node, name[/a50_pub], pid[35583]
[xmlrpc][INFO] 2024-07-18 15:09:09,450: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2024-07-18 15:09:09,451: Started XML-RPC server [http://ubuntu:43633/]
[rospy.impl.masterslave][INFO] 2024-07-18 15:09:09,451: _ready: http://ubuntu:43633/
[rospy.init][INFO] 2024-07-18 15:09:09,452: ROS Slave URI: [http://ubuntu:43633/]
[rospy.registration][INFO] 2024-07-18 15:09:09,453: Registering with master node http://localhost:11311
[xmlrpc][INFO] 2024-07-18 15:09:09,453: xml rpc node: starting XML-RPC server
[rospy.init][INFO] 2024-07-18 15:09:09,553: registered with master
[rospy.rosout][INFO] 2024-07-18 15:09:09,553: initializing /rosout core topic
[rospy.registration][ERROR] 2024-07-18 15:09:09,561: [Errno 111] Connection refused
Unable to register with master node [http://localhost:11311]: master may not be running yet. Will keep trying.
[rospy.core][INFO] 2024-07-18 15:11:18,020: signal_shutdown [signal-2]
[rospy.registration][WARNING] 2024-07-18 15:11:18,022: cannot unregister with master due to network issues
[rospy.impl.masterslave][INFO] 2024-07-18 15:11:18,022: signal-2
[rospy.core][INFO] 2024-07-18 15:11:19,324: signal_shutdown [signal-2]
[rospy.core][INFO] 2024-07-18 15:11:19,481: signal_shutdown [signal-2]
[rospy.rosout][INFO] 2024-07-18 15:11:23,123: connected to core topic /rosout
[rospy.simtime][ERROR] 2024-07-18 15:11:23,128: Unable to initialize /clock: [Errno 111] Connection refused
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/simtime.py", line 79, in init_simtime
    if not _is_use_simtime():
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/simtime.py", line 60, in _is_use_simtime
    code, msg, val = m.getParam(rospy.names.get_caller_id(), _USE_SIMTIME)
  File "/usr/lib/python3.8/xmlrpc/client.py", line 1109, in __call__
    return self.__send(self.__name, args)
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/core.py", line 669, in _ServerProxy__request
    return xmlrpcclient.ServerProxy._ServerProxy__request(
  File "/usr/lib/python3.8/xmlrpc/client.py", line 1450, in __request
    response = self.__transport.request(
  File "/usr/lib/python3.8/xmlrpc/client.py", line 1153, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python3.8/xmlrpc/client.py", line 1165, in single_request
    http_conn = self.send_request(host, handler, request_body, verbose)
  File "/usr/lib/python3.8/xmlrpc/client.py", line 1278, in send_request
    self.send_content(connection, request_body)
  File "/usr/lib/python3.8/xmlrpc/client.py", line 1308, in send_content
    connection.endheaders(request_body)
  File "/usr/lib/python3.8/http/client.py", line 1251, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1011, in _send_output
    self.send(msg)
  File "/usr/lib/python3.8/http/client.py", line 951, in send
    self.connect()
  File "/usr/lib/python3.8/http/client.py", line 922, in connect
    self.sock = self._create_connection(
  File "/usr/lib/python3.8/socket.py", line 808, in create_connection
    raise err
  File "/usr/lib/python3.8/socket.py", line 796, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

[rospy.core][INFO] 2024-07-18 15:11:27,300: signal_shutdown [atexit]
